### ISSUE TITLE
How do you guard against opening binary files?

### ISSUE THREAD

**Issue by dominikwilkowski** [andre-vm/rev_buf_reader#6]
Hi there,

I got a thing I use to open user defined files and I need to make sure I catch errors when rust is trying to open a file that's not utf-8.

```rust
use rev_buf_reader::RevBufReader;

fn main() -> Result<(), io::Error> {
    let this_path = "binary.file";
    let limit = 50;

    let file = fs::File::open(this_path)?; // <-- this works fine
    let buf = RevBufReader::new(file); // <-- this fails with "stream did not contain valid UTF-8"
    let lines = buf
        .lines()
        .take(limit)
        .map(|l| l.expect("Could not parse line"))
        .collect::<Vec<String>>()
        .join("\n");
}
```

Currently `RevBufReader` does not implement the `Try` trait. What would be the best way to do this?

**Comment by andre-vm** [comment]
Hi @dominikwilkowski! Thank you for getting in touch!

To be honest, it's been a while since the last time I made changes to this lib, and I haven't been using Rust lately either. But the idea of this lib is to mimic the behavior of [std::io::BufReader](https://doc.rust-lang.org/std/io/struct.BufReader.html), just in reverse order. If I remember correctly, neither `std::io::BufReader` or `RevBufReader` contain any logic regarding byte encoding, that's rather handled by the internal reader, which is completely abstracted by the [std::io::Read](https://doc.rust-lang.org/std/io/trait.Read.html) trait. Maybe instead of passing an `fs::File` to `RevBufReader::new`, try wrapping the file in some decoder struct that implements the `std::io::Read` trait and pass it instead. [This StackOverflow question](https://stackoverflow.com/questions/64040851/how-can-i-read-a-non-utf8-file-line-by-line-in-rust) may be helpful.

Also, I would suggest you replace `RevBufReader` in your code with `std::io::BufReader` and try to make it work with non-UTF-8 files. When you find a way, change it back to `RevBufReader`. If it works with `std::io::BufReader` but not with `RevBufReader`, then I probably made a mistake somewhere in the lib. In that case, I'll take some time to try to fix it.

**Comment by dominikwilkowski** [comment]
Thank you @andre-vm 
Let me have a look after the weekend and see how far I get.
Appreciate the crate btw. So far the best way for me to read the last n lines of a huge file without having to load it entirely into memory.

**Comment by dominikwilkowski** [comment]
Ok I had a stab at it. This works fine:

```rust
use std::io::BufReader;
use std::fs;
use std::io;
use std::io::BufRead;
use encoding_rs::UTF_8;
use encoding_rs_io::DecodeReaderBytesBuilder;

fn main() -> Result<(), io::Error> {
	let this_path = "./.DS_Store"; // best file I could think of quickly
	let limit = 50;

	let file = fs::File::open(this_path)?;
	let reader = BufReader::new(
		DecodeReaderBytesBuilder::new()
			.encoding(Some(UTF_8))
			.build(file)
	);
	reader
		.lines()
		.take(limit)
		.map(|l| l.expect("Could not parse line"))
		.collect::<Vec<String>>()
		.join("\n");

	Ok(())
}
```

But this fails:

```rust
use rev_buf_reader::RevBufReader; // <-- Just replaced this
use std::fs;
use std::io;
use std::io::BufRead;
use encoding_rs::UTF_8;
use encoding_rs_io::DecodeReaderBytesBuilder;

fn main() -> Result<(), io::Error> {
	let this_path = "./.DS_Store";
	let limit = 50;

	let file = fs::File::open(this_path)?;
	let reader = RevBufReader::new( // <-- Just replaced this
		DecodeReaderBytesBuilder::new()
			.encoding(Some(UTF_8))
			.build(file)
	);
	reader
		.lines()
		.take(limit)
		.map(|l| l.expect("Could not parse line"))
		.collect::<Vec<String>>()
		.join("\n");

	Ok(())
}
```

With this error:

```sh
λ cargo run
   Compiling checkfile v1.0.0 (/path/to/checkfile)
error[E0277]: the trait bound `DecodeReaderBytes<File, Vec<u8>>: Seek` is not satisfied
   --> src/main.rs:101:3
    |
100 |       let reader = RevBufReader::new(
    |                    ----------------- required by a bound introduced by this call
101 | /         DecodeReaderBytesBuilder::new()
102 | |             .encoding(Some(UTF_8))
103 | |             .build(file)
    | |________________________^ the trait `Seek` is not implemented for `DecodeReaderBytes<File, Vec<u8>>`
    |
    = help: the following other types implement trait `Seek`:
              &File
              &mut S
              Box<S>
              BufReader<R>
              BufWriter<W>
              File
              RevBufReader<R>
              std::io::Cursor<T>
              std::io::Empty
note: required by a bound in `RevBufReader::<R>::new`
   --> /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rev_buf_reader-0.3.0/src/lib.rs:109:16
    |
109 | impl<R: Read + Seek> RevBufReader<R> {
    |                ^^^^ required by this bound in `RevBufReader::<R>::new`

error[E0599]: the method `lines` exists for struct `RevBufReader<DecodeReaderBytes<File, Vec<u8>>>`, but its trait bounds were not satisfied
   --> src/main.rs:106:4
    |
105 | /     reader
106 | |         .lines()
    | |         -^^^^^ method cannot be called on `RevBufReader<DecodeReaderBytes<File, Vec<u8>>>` due to unsatisfied trait bounds
    | |_________|
    | 
    |
   ::: /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rev_buf_reader-0.3.0/src/lib.rs:102:1
    |
102 |   pub struct RevBufReader<R> {
    |   -------------------------- doesn't satisfy `_: BufRead`
    |
   ::: /path/to/.cargo/registry/src/index.crates.io-6f17d22bba15001f/encoding_rs_io-0.1.7/src/lib.rs:355:1
    |
355 |   pub struct DecodeReaderBytes<R, B> {
    |   ---------------------------------- doesn't satisfy `DecodeReaderBytes<File, Vec<u8>>: Seek`
    |
    = note: the following trait bounds were not satisfied:
            `DecodeReaderBytes<File, Vec<u8>>: Seek`
            which is required by `RevBufReader<DecodeReaderBytes<File, Vec<u8>>>: BufRead`
            `RevBufReader<DecodeReaderBytes<File, Vec<u8>>>: BufRead`
            which is required by `&mut RevBufReader<DecodeReaderBytes<File, Vec<u8>>>: BufRead`

warning: unused import: `std::io::BufRead`
  --> src/main.rs:91:5
   |
91 | use std::io::BufRead;
   |     ^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
warning: `checkfile` (bin "checkfile") generated 1 warning
error: could not compile `checkfile` (bin "checkfile") due to 2 previous errors; 1 warning emitted
```

Looks like it fails on requiring the `Seek` trait?

**Comment by andre-vm** [comment]
Oh, I see.. sorry, I didn't realize `DecodeReaderBytes` doesn't implement `Seek`. It actually makes sense, as it should be able to work with all kinds of readers, not only files.

`RevBufReader` is also intended to work with all kinds of readers, but it does really need the internal reader to implement `Seek`. That's because we need to go to the end of the stream (`seek(SeekFrom::End(0))`) in order to start reading it backwards. For example, you wouldn't be able to use `RevBufReader` on a TCP or WebSocket stream, since you haven't received all the bytes until the socket is closed, and thus we can't get to the end of it in advance. In case your reader doesn't implement `Seek` the only other way to read files backwards is, as you said, load it entirely into memory. And that falls out of the scope of this lib.

You may request [encoding_rs_io](https://github.com/BurntSushi/encoding_rs_io) maintainers to implement `Seek` for `DecodeReaderBytes<R, B> when R: Seek`, although that crate seems not to have any updates since Feb 2020. I'm also not sure how difficult it is to do this change, maybe you'd like to give yourself a try. Otherwise, you may need to look for other ways of reading non-UTF-8 files.

I know this doesn't help much, I'm sorry. I hope to have at least clarified things a bit.

**Comment by dominikwilkowski** [comment]
No worries at all. I close the issue for now.
